package com.dragovorn.dotaapi.match;

/**
 * *************************************************************************
 * (c) Dragovorn 2016. This file was created by Andrew at 01:08 AM.
 * as of July 15 2016 the project DotaAPI is Copyrighted.
 * *************************************************************************
 */
public enum Item {
    EMPTY("Empty", 0),
    BLINK_DAGGER("Blink Dagger", 1),
    BLADES_OF_ATTACK("Blades of Attack", 2),
    BROADSWORD("Broadsword", 3),
    CHAINMAIL("Chainmail", 4),
    CLAYMORE("Claymore", 5),
    HELM_OF_IRON_WILL("Helm of Iron Will", 6),
    JAVELIN("Javelin", 7),
    MITHRIL_HAMMER("Mithril Hammer", 8),
    PLATEMAIL("Platemail", 9),
    QUARTERSTAFF("Quarterstaff", 10),
    QUELLING_BLADE("Quelling Blade", 11),
    RING_OF_PROTECTION("Ring of Protection", 12),
    GAUNTLETS_OF_STRENGTH("Gauntlets of Strength", 13),
    SLIPPERS_OF_AGILITY("Slippers of Agility", 14),
    MAANTLE_OF_INTELLIGENCE("Mantle of Intelligence", 15),
    IRON_BRANCH("Iron Branch", 16),
    BELT_OF_STRENGTH("Belt of Strength", 17),
    BAND_OF_ELVENSKIN("Band of Elvenskin", 18),
    ROBE_OF_THE_MAGI("Robe of the Magi", 19),
    CIRCLET("Circlet", 20),
    OGRE_CLUB("Ogre Club", 21),
    BLADE_OF_ALACRITY("Blade of Alacrity", 22),
    STAFF_OF_WIZARDRY("Staff of Wizardry", 23),
    ULTIMATE_ORB("Ultimate Orb", 24),
    GLOVES_OF_HASTE("Gloves of Haste", 25),
    MORBID_MASK("Morbid Mask", 26),
    RING_OF_REGEN("Ring of Regen", 27),
    SAGES_MASK("Sage's Mask", 28),
    BOOTS_OF_SPEED("Boots of Speed", 29),
    GEM_OF_TRUE_SIGHT("Gem of True Sight", 30),
    CLOAK("Cloak", 31),
    TALISMAN_OF_EVASION("Talisman of Evasion", 32),
    CHEESE("Cheese", 33),
    MAGIC_STICK("Magic Stick", 34),
    RECIPE_MAGIC_WAND("Recipe: Magic Wand", 35),
    MAGIC_WAND("Magic Wand", 36),
    GHOST_SCEPTER("Ghost Scepter", 37),
    CLARITY("Clarity", 38),
    HEALING_SALVE("Healing Salve", 39),
    DUST_OF_APPEARANCE("Dust of Appearance", 40),
    BOTTLE("Bottle", 41),
    OBSERVER_WARD("Observer Ward", 42),
    SENTRY_WARD("Sentry Ward", 43),
    TANGO("Tango", 44),
    COURIER("Courier", 45),
    TP_SCROLL("Town Portal Scroll", 46),
    RECIPE_BOOTS_OF_TRAVEL("Recipe: Boots of Travel (Level: 1)", 47),
    BOOTS_OF_TRAVEL("Boots of Travel (Level: 1)", 48),
    RECIPE_PHASE_BOOTS("Recipe: Phase Boots", 49),
    PHASE_BOOTS("Phase Boots", 50),
    DEMON_EDGE("Demon Edge", 51),
    EAGLESONG("Eaglesong", 52),
    REAVER("Reaver", 53),
    SCARED_RELIC("Sacred Relic", 54),
    HYPERSTONE("Hyperstone", 55),
    RING_OF_HEALTH("Ring of Health", 56),
    VOID_STONE("Void Stone", 57),
    MYSTIC_STAFF("Mystic Staff", 58),
    ENERGY_BOOSTER("Energy Booster", 59),
    POINT_BOOSTER("Point Booster", 60),
    VITALITY_BOOSTER("Vitality Booster", 61),
    RECIPE_POWER_TREADS("Recipe: Power Treads", 62),
    POWER_TREADS("Power Treads", 63),
    RECIPE_HAND_OF_MIDAS("Recipe: Hand of Midas", 64),
    HAND_OF_MIDAS("Hand of Midas", 65),
    RECIPE_OBLIVION_STAFF("Recipe: Oblivion Staff", 66),
    OBLIVION_STAFF("Oblivion Staff", 67),
    RECIPE_PERSEVERANCE("Recipe: Perseverance", 68),
    PERSERVERANCE("Perseverance", 69),
    RECIPE_POOR_MANS_SHIELD("Recipe: Poor Man's Shield", 70),
    POOR_MANS_SHIELD("Poor Man's Shield", 71),
    RECIPE_BRACER("Recipe: Bracer", 72),
    BRACER("Bracer", 73),
    RECIPE_WRAITH_BAND("Recipe: Wraith Band", 74),
    WRAITH_BAND("Wraith Band", 75),
    RECIPE_NULL_TALISMAN("Recipe: Null Talisman", 76),
    NULL_TALISMAN("Null Talisman", 77),
    RECIPE_MEKANSM("Recipe: Mekansm", 78),
    MEKANSM("Mekansm", 79),
    RECIPE_VLADMIRS_OFFERING("Recipe: Vladmir's Offering", 80),
    VLADMIRS_OFFERING("Vladmir's Offering", 81),
    FLYING_COURIER("Flying Courier", 84),
    RECIPE_BUCKLER("Recipe: Buckler", 85),
    BUCKLER("Buckler", 86),
    RECIPE_RING_OF_BASILIUS("Recipe: Ring of Basilius", 87),
    RING_OF_BASILIUS("Ring of Basilius", 88),
    RECIPE_PIPE_OF_INSIGHT("Recipe: Pipe of Insight", 89),
    PIPE_OF_INSIGHT("Pipe of Insight", 90),
    RECIPE_URN_OF_SHADOWS("Recipe: Urn of Shadows", 91),
    URN_OF_SHADOWS("Urn of Shadows", 92),
    RECIPE_HEADDRESS("Recipe: Headdress", 93),
    HEADDRESS("Headdress", 94),
    RECIPE_SCYTHE_OF_VYSE("Recipe: Scythe of Vyse", 95),
    SCYTHE_OF_VYSE("Scythe of Vyse", 96),
    RECIPE_ORCHID_OF_MALEVOLENCE("Recipe: Orchid of Malevolence", 97),
    ORCHID_OF_MALEVOLENCE("Orchid of Malevolence", 98),
    RECIPE_EULS_SCEPTER_OF_DIVINITY("Recipe: Eul's Scepter of Divinity", 99),
    EULS_SCEPTER_OF_DIVINITY("Eul's Scepter of Divinity", 100),
    RECIPE_FORCE_STAFF("Recipe: Force Staff", 101),
    FORCE_STAFF("Force Staff", 102),
    RECIPE_DAGON("Recipe: Dagon (Level: 1)", 103),
    DAGON("Dagon (Level: 1)", 104),
    RECIPE_NECRONOMICON("Recipe: Necronomicon (Level: 1)", 105),
    NECRONOMICON("Necronomicon (Level: 1)", 106),
    RECIPE_AGHANIMS_SCEPTER("Recipe: Aghanim's Scepter", 107),
    AGHANIMS_SCEPTER("Aghanim's Scepter", 108),
    RECIPE_REFRESHER_ORB("Recipe: Refresher Orb", 109),
    REFRESHER_ORB("Refresher Orb", 110),
    RECIPE_ASSAULT_CURIASS("Recipe: Assault Cuirass", 111),
    ASSAULT_CURIASS("Assault Cuirass", 112),
    RECIPE_HEART_OF_TARRASQUE("Recipe: Heart of Tarrasque", 113),
    HEART_OF_TARRASQUE("Heart of Tarrasque", 114),
    RECIPE_BLACK_KING_BAR("Recipe: Black King Bar", 115),
    BLACK_KING_BAR("Black King Bar", 116),
    AEGIS_OF_THE_IMMORTAL("Aegis of the Immortal", 117),
    RECIPE_SHIVAS_GUARD("Recipe: Shiva's Guard", 118),
    SHIVAS_GUARD("Shiva's Guard", 119),
    RECIPE_BLOODSTONE("Recipe: Bloodstone", 120),
    BLOODSTONE("Bloodstone", 121),
    RECIPE_LINKENS_SPHERE("Recipe: Linken's Sphere", 122),
    LINKENS_SPHERE("Linken's Sphere", 123),
    RECIPE_VANGUARD("Recipe: Vanguard", 124),
    VANGUARD("Vanguard", 125),
    RECIPE_BLADE_MAIL("Recipe: Blade Mail", 126),
    BLADE_MAIL("Blade Mail", 127),
    RECIPE_SOUL_BOOSTER("Recipe: Soul Booster", 128),
    SOUL_BOOSTER("Soul Booster", 129),
    RECIPE_HOOD_OF_DEFIANCE("Recipe: Hood Of Defiance", 130),
    HOOD_OF_DEFIANCE("Hood Of Defiance", 131),
    RECIPE_DIVINE_RAPIER("Recipe: Divine Rapier", 132),
    DIVINE_RAPIER("Divine Rapier", 133),
    RECIPE_MONKEY_KING_BAR("Recipe: Monkey King Bar", 134),
    MONKEY_KING_BAR("Monkey King Bar", 135),
    RECIPE_RADIANCE("Recipe: Radiance", 136),
    RADIANCE("Radiance", 137),
    RECIPE_BUTTERFLY("Recipe: Butterfly", 138),
    BUTTERFLY("Butterfly", 139),
    RECIPE_DAEDALUS("Recipe: Daedalus", 140),
    DAEDALUS("Daedalus", 141),
    RECIPE_SKULL_BASHER("Recipe: Skull Basher", 142),
    SKULL_BASHER("Skull Basher", 143),
    RECIPE_BATTLE_FURY("Recipe: Battle Fury", 144),
    BATTLE_FURY("Battle Fury", 145),
    RECIPE_MANTA_STYLE("Recipe: Manta Style", 146),
    MANTA_STYLE("Manta Style", 147),
    RECIPE_CRYSTALYS("Recipe: Crystalys", 148),
    CRYSTALYS("Crystalys", 149),
    RECIPE_ARMLET_OF_MORDIGGIAN("Recipe: Armlet of Mordiggian", 150),
    ARMLET_OF_MORDIGGIAN("Armlet of Mordiggian", 151),
    SHADOW_BLADE("Shadow Blade", 152),
    RECIPE_SANGE_AND_YASHA("Recipe: Sange and Yasha", 153),
    SANGE_AND_YASHA("Sange and Yasha", 154),
    RECIPE_SATANIC("Recipe: Satanic", 155),
    SATANIC("Satanic", 156),
    RECIPE_MJOLLNIR("Recipe: Mjollnir", 157),
    MJOLLNIR("Mjollnir", 158),
    RECIPE_EYE_OF_SKADI("Recipe: Eye of Skadi", 159),
    EYE_OF_SKADI("Eye of Skadi", 160),
    RECIPE_SANGE("Recipe: Sange", 161),
    SANGE("Sange", 162),
    RECIPE_HELM_OF_THE_DOMINATOR("Recipe: Helm of the Dominator", 163),
    HELM_OF_THE_DOMINATOR("Helm of the Dominator", 164),
    RECIPE_MAELSTORM("Recipe: Maelstorm", 165),
    MAELSTORM("Maelstorm", 166),
    RECIPE_DESOLATOR("Recipe: Desolator", 167),
    DESOLATOR("Desolator", 168),
    RECIPE_YASHA("Recipe: Yasha", 169),
    YASHA("Yasha", 170),
    RECIPE_MASK_OF_MADNESS("Recipe: Mask of Madness", 171),
    MASK_OF_MADNESS("Mask of Madness", 172),
    RECIPE_DIFFUSAL_BLADE("Recipe: Diffusal Blade (Level: 1)", 173),
    DIFFUSAL_BLADE("Diffusal Blade (Level: 1)", 174),
    RECIPE_ETHEREAL_BLADE("Recipe: Ethereal Blade", 175),
    ETHEREAL_BLADE("Ethereal Blade", 176),
    RECIPE_SOUL_RING("Recipe: Soul Ring", 177),
    SOUL_RING("Soul Ring", 178),
    RECIPE_ARCANE_BOOTS("Recipe: Arcane Boots", 179),
    ARCANE_BOOTS("Arcane Boots", 180),
    ORB_OF_VENOM("Orb of Venom", 181),
    STOUT_SHIELD("Stout Shield", 182),
    RECIPE_SHADOW_BLADE("Recipe: Shadow Blade", 183),
    RECIPE_DRUMS_OF_ENDURANCE("Recipe: Drums of Endurance", 184),
    DRUMS_OF_ENDURANCE("Drums of Endurance", 185),
    RECIPE_MEDALLION_OF_COURAGE("Recipe: Medallion of Courage", 186),
    MEDALLION_OF_COURAGE("Medallion of Courage", 187),
    SMOKE_OF_DECEIT("Smoke of Deceit", 188),
    RECIPE_VEIL_OF_DISCORD("Recipe: Veil of Discord", 189),
    VEIL_OF_DISCORD("Veil of Discord", 190),
    RECIPE_NECRONOMICON_2("Recipe: Necronomicon (Level: 2)", 191),
    RECIPE_NECTONOMICON_3("Recipe: Necronomicon (Level: 3)", 192),
    NECRONOMICON_2("Necronomicon (Level: 2)", 193),
    NECRONOMICON_3("Necronomicon (Level: 3)", 194),
    RECIPE_DIFFUSAL_BLADE_2("Recipe: Diffusal Blade (Level: 2)", 195),
    DIFFUSAL_BLADE_2("Diffusal Blade (Level: 2)", 196),
    RECIPE_DAGON_2("Recipe: Dagon (Level: 2)", 197),
    RECIPE_DAGON_3("Recipe: Dagon (Level: 3)", 198),
    RECIPE_DAGON_4("Recipe: Dagon (Level: 4)", 199),
    RECIPE_DAGON_5("Recipe: Dagon (Level: 5)", 200),
    DAGON_2("Dagon (Level: 2)", 201),
    DAGON_3("Dagon (Level: 3)", 202),
    DAGON_4("Dagon (Level: 4)", 203),
    DAGON_5("Dagon (Level: 5)", 204),
    RECIPE_ROD_OF_ATOS("Recipe: Rod of Atos", 205),
    ROD_OF_ATOS("Rod of Atos", 206),
    RECIPE_ABYSSAL_BLADE("Recipe: Abyssal Blade", 207),
    ABYSSAL_BLADE("Abyssal Blade", 208),
    RECIPE_HEAVENS_HALBERD("Recipe: Heaven's Halberd", 209),
    HEAVENS_HALBERD("Heaven's Halberd", 210),
    ;


    private String name;

    private int value;

    Item(String name, int value) {
        this.name = name;
        this.value = value;
    }

    public String getName() {
        return name;
    }

    public int getValue() {
        return value;
    }
}